<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.at.rt.data.warehouse</groupId>
        <artifactId>rt-data-warehouse</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>rt-warehouse-paimon-test</artifactId>
    <packaging>jar</packaging>

    <name>RT : Warehouse : Paimon : Test</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <consumer.lib>${basedir}/lib</consumer.lib>
    </properties>

    <dependencies>

        <!-- https://mvnrepository.com/artifact/org.apache.flink/flink-table-api-java-bridge -->
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-api-java-bridge</artifactId>
            <version>1.17.1</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.hive</groupId>
            <artifactId>hive-exec</artifactId>
            <version>3.1.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.paimon</groupId>
            <artifactId>paimon-flink-1.17.1-1.0</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.paimon</groupId>
            <artifactId>paimon-hive-connector-3.1-1.0</artifactId>
        </dependency>

    </dependencies>
</project>
