isLocal: true

# Flink Execute Environment
execute:
  env:
    - streaming
    - batch

pipeline:
  operator-chaining: false

default:
  parallelism: 1

restart:
  strategy:
    - fix:
        attempts: 3
        delay: 60000 # ms

checkpoint:
  enable: true
  type: AT_LEAST_ONCE # 1 AT_LEAST_ONCE 0  EXACTLY_ONCE
  unaligned: false # EXACTLY_ONCE 模式下这里设置 true 才有意义 Unaligned checkpoints are currently not supported for custom partitioners, as rescaling is not guaranteed to work correctly. The user can force Unaligned Checkpoints by using 'execution.checkpointing.unaligned.forced'
  interval: 10000 # ms
  min-between: 500 # ms
  timeout: 10000 # ms
  failure-num: 5
  state-storage: filesystem
  state-dir: hdfs://hadoop102:8020/rt/checkpoint/DWDTradeCartAdd
